# Generated by Django 6.0 on 2025-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='AppUser',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
