# Generated by Django 6.0 on 2026-04-06 17:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='team_comments/'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='team_posts/'),
        ),
    ]
